import Head from 'next/head'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Nayer Raja</h1>

    {/* Sidebar */}
    <Sidebar />

    {/* Feed */}

    {/* Widgets */}

    {/* Model */}

      </main>

    </div>
  )
}
